In [1]:
import numpy as np

In [2]:
lista = [10, 33, 80, 100]
listb = [22, 12, 6, 89]
listc = [15, 6, 82, 54]

In [3]:
na = np.array(lista)

In [4]:
print(type(lista))

<class 'list'>


In [5]:
print(type(na))

<class 'numpy.ndarray'>


In [6]:
print(na.shape)

(4,)


In [7]:
print(na)

[ 10  33  80 100]


In [8]:
print(na ** 2)

[  100  1089  6400 10000]


In [9]:
print(na.ndim)

1


In [10]:
nb = np.array([lista, listb, listc])
nc = np.array([[2, 3], [1, 0], [4, 7]])

In [11]:
print(nb.ndim)

2


In [12]:
print(nb.shape)

(3, 4)


In [13]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  89]
 [ 15   6  82  54]]


In [14]:
print(nb.size)

12


In [15]:
print(nc.size)

6


In [16]:
print(nc)

[[2 3]
 [1 0]
 [4 7]]


In [17]:
print(nc[2][0])

4


In [18]:
print(nc.dtype)

int64


In [19]:
nb = np.array([lista, listb, listc], dtype='uint16')

In [21]:
print(nb.dtype)

uint16


In [22]:
print(nc.itemsize)

8


In [23]:
print(nb.itemsize)

2


In [24]:
print(nb.nbytes)

24


In [25]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  89]
 [ 15   6  82  54]]


In [30]:
nd = np.array([[2, 7, 4, 3], [1, 9, 8, 7], [3, 5, 8, 1]])

In [28]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  89]
 [ 15   6  82  54]]


In [31]:
print(nd)

[[2 7 4 3]
 [1 9 8 7]
 [3 5 8 1]]


In [32]:
print(na + nd)

[[ 12  40  84 103]
 [ 11  42  88 107]
 [ 13  38  88 101]]


In [33]:
ne = np.zeros((3, 4))

print(ne)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
print(ne.dtype)

float64


In [36]:
nf = np.ones((2, 3))

print(nf)

[[1. 1. 1.]
 [1. 1. 1.]]


## ndarray indexing

In [37]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  89]
 [ 15   6  82  54]]


In [38]:
print(nb[2][2])

82


In [39]:
print(nb[:, 0:3])

[[10 33 80]
 [22 12  6]
 [15  6 82]]


In [41]:
print(nb[0:2])

[[ 10  33  80 100]
 [ 22  12   6  89]]


In [43]:
print(nb[0:2][:2])

[[ 10  33  80 100]
 [ 22  12   6  89]]


In [44]:
print(nb[0:2, :2])

[[10 33]
 [22 12]]


In [45]:
nb[2][1] = 70

In [46]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  89]
 [ 15  70  82  54]]


In [47]:
print(nb.mean())

47.75


In [48]:
print(nb.sum())

573


In [49]:
print(nb.min())

6


In [50]:
print(nb.reshape(6, 2))

[[ 10  33]
 [ 80 100]
 [ 22  12]
 [  6  89]
 [ 15  70]
 [ 82  54]]


In [53]:
print(nb.reshape(4, -1))

[[ 10  33  80]
 [100  22  12]
 [  6  89  15]
 [ 70  82  54]]


In [54]:
ng = np.linspace(2, 3, num=5)

In [55]:
print(ng)

[2.   2.25 2.5  2.75 3.  ]


In [56]:
ng = np.linspace(2, 3, num=5, endpoint=False)

In [57]:
print(ng)

[2.  2.2 2.4 2.6 2.8]


In [58]:
ng = np.linspace(2, 3, num=5, retstep=True)

In [59]:
print(ng)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [60]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  89]
 [ 15  70  82  54]]


In [62]:
print(nb.flatten())

[ 10  33  80 100  22  12   6  89  15  70  82  54]


In [63]:
nh = np.arange(6)

In [64]:
print(nh)

[0 1 2 3 4 5]


In [65]:
for i in nc:
    print(i)

[2 3]
[1 0]
[4 7]


In [66]:
for i in nc.flat:
    print(i)

2
3
1
0
4
7


In [67]:
ni = nb

In [68]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  89]
 [ 15  70  82  54]]


In [69]:
nb[1][-1]

89

In [71]:
ni[1][-1] = 58

print(nb[1][-1])

58


In [72]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  58]
 [ 15  70  82  54]]


In [73]:
nj = nb.copy()

nj[1][-1] = 11

In [74]:
print(nj)

[[ 10  33  80 100]
 [ 22  12   6  11]
 [ 15  70  82  54]]


In [76]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  58]
 [ 15  70  82  54]]


In [77]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  58]
 [ 15  70  82  54]]


In [79]:
print(nb.transpose())

[[ 10  22  15]
 [ 33  12  70]
 [ 80   6  82]
 [100  58  54]]


In [81]:
print(np.where(nb == 12))

(array([1]), array([1]))


In [82]:
print(np.where(nb > 50))

(array([0, 0, 1, 2, 2, 2]), array([2, 3, 3, 1, 2, 3]))


In [83]:
print(nb)

[[ 10  33  80 100]
 [ 22  12   6  58]
 [ 15  70  82  54]]


In [84]:
nk = np.array([["hi", "hello"], ["rr", "tt"]])

In [85]:
print(nk)

[['hi' 'hello']
 ['rr' 'tt']]
